name = "ObjectFile"
uuid = "d8793406-e978-5875-9003-1fc021f44a92"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "0.4.1"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StructIO = "53d494c1-5632-5724-8f4c-31dff12d585f"


[compat]
Reexport = "0.2, 1.0"
StructIO = "0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
